@startuml
skinparam sequence {
    ParticipantBorderColor Black
    ParticipantBackgroundColor #EEE
    ParticipantBorderColor Black
    ArrowColor Black
    ActorBorderColor Black
    ActorBackgroundColor #EEE
    LifeLineBorderColor Black
}

actor User
User -> View                    : click \non "link"
View -> Interpretation          : navigation request \nto substructure
Interpretation -> NavigationService : navigation request \nfrom interpretation \nto substructure
NavigationService -> Presenter         : presentation request \nwith caller and substructure
@enduml