@startuml
skinparam sequence {
    ParticipantBorderColor Black
    ParticipantBackgroundColor #EEE
    ParticipantBorderColor Black
    ArrowColor Black
    ActorBorderColor Black
    ActorBackgroundColor #EEE
    LifeLineBorderColor Black
}

title Navigate Structure

User -> Interpretation  : "click on element"
Interpretation -> NavigationService : request_navigation
NavigationService -> Presenter : notify_observers
Presenter -> InterpretationService : interpret(structure)
InterpretationService -> InterpretationService : "magic"
InterpretationService -> Presenter  : interpretation
Presenter -> Presenter  :   display(interpretation)
Presenter -> User : "navigation complete"

@enduml