FROM fedora:37

RUN dnf -y install python3 python3-pip python3-gobject gcc ccache make meson mold uncrustify desktop-file-utils \
    gtk4-devel libhandy-devel libadwaita-devel docbook-style-xsl \
    appstream libxslt gcovr xorg-x11-server-Xvfb gtk-doc gi-docgen \
    vulkan-headers bash-completion itstool util-linux git  && rm -rf /var/cache

ADD requirements.txt ./

RUN pip install -r requirements.txt && rm requirements.txt
