services:
  - docker:stable-dind

stages:
  - imagebuild
  - prebuild
  - build
  - test
  - build_tags
  - deploy

###############################################################################
# Documentation & Project include
###############################################################################

include:
  - local: '/.gitlab/docs/ci.yml'
  - local: '/.gitlab/project/ci.yml'