FROM python:3.8

RUN apt-get update && apt-get install -y \
  make \
  git \
  python3-gi \
  python3-gi-cairo \
  gir1.2-gtk-3.0

ADD requirements.txt ./

RUN pip install -r requirements.txt && rm requirements.txt
