FROM python:3.8-alpine

RUN apk --update --no-cache add \
  make \
  git \
  python3-gi \
  python3-gi-cairo \
  gir1.2-gtk-3.0

ADD requirements.txt ./

RUN pip install -r requirements.txt && rm requirements.txt
