@startuml sequence of interpretation
skinparam sequence {
    ParticipantBorderColor Black
    ParticipantBackgroundColor #EEE
    ParticipantBorderColor Black
    ArrowColor Black
    ActorBorderColor Black
    ActorBackgroundColor #EEE
    LifeLineBorderColor Black
}

title Interpretation Service

Caller -> InterpretationService : interpret(structure)
InterpretationService -> TypeRegistry : get types
TypeRegistry -> InterpretationService : list of types

InterpretationService -> InterpretationService : filter types
InterpretationService -> InterpretationService : sort types
InterpretationService -> InterpretationService : create interpretation

InterpretationService -> Caller : interpretation

@enduml