@startuml Type Extension Overview

hide members
hide methods

skinparam class {
    BackgroundColor #EEE
    ArrowColor Black
    BorderColor Black
}

title Type Extension Overview

package "TypeExtension" {
    class Entrypoint {}
    class Extension {}
    class Type {}
    class TypeView {}
    class TypeViewFactory {}
    class Action {}

    Entrypoint -down-> Extension : creates

    Extension ---> Type : registers
    Extension -down-> TypeViewFactory : registers
    Extension -right-> Action : registers

    TypeViewFactory -down-> TypeView  : creates
    Action -down-> Type : manipulates

    TypeView -up-> Type : displays

    TypeViewFactory -[hidden]right-> Action
    Type -[hidden]right-> Action
}

@enduml