@startuml interfaces and services

skinparam rectangle {
    BackgroundColor #EEE
    ArrowColor Black
    BorderColor Black
    roundCorner 25
}

skinparam rectangle<<out-of-scope>> {
    BorderColor #CCC
    BackgroundColor #FFF
    FontColor #555
}

title Interfaces and Services



package "Black Fennec" <<Frame>> as BF {
    rectangle "Presentation System" as PS
    rectangle "Document System" as DS
    rectangle Structure
    rectangle "Type System" as TS
    rectangle "Actions System" as AS

    TS          -->     Structure

    AS          -->   TS
    AS          -->     Structure
    
    DS          -->     Structure

    PS          -->   TS
    PS          -->     Structure
    PS          -->     DS

}

rectangle Types
rectangle Actions
rectangle Views
rectangle Presenters
rectangle "Mime Types" as MT
rectangle "Resource Types" as RT
rectangle "User Data" as UD <<out-of-scope>>

Types           -->         TS
Actions         -->         AS
Views           -->         PS
Presenters      -->         PS
MT              -->         DS
RT              -->         DS
UD              -->         DS

Types           -[hidden]right->        BF

@enduml
