@startuml architecture overview

skinparam rectangle {
    BackgroundColor #EEE
    ArrowColor Black
    BorderColor Black
    roundCorner 25
}

skinparam rectangle<<out-of-scope>> {
    BorderColor #CCC
    BackgroundColor #FFF
    FontColor #555
}

skinparam rectangle<<core>> {
    roundCorner 1000
}

title Architecture Overview

rectangle Types
rectangle Actions
rectangle Views
rectangle Presenters
rectangle "Mime Types" as MT
rectangle "Resource Types" as RT
rectangle "User Data" as UD <<out-of-scope>>
rectangle "Black Fennec" as BF <<core>>

Types           -down->       BF
Actions         -down->         BF
Views           -left->         BF
Presenters      -left->         BF
MT              -right->         BF
RT              -right->         BF
UD              -up->         BF

Presenters      -[hidden]up->   Views
MT              -[hidden]up->   RT

@enduml
